### ISSUE TITLE
Enrich the homepage

### ISSUE THREAD

**Issue by smimram** [savonet/savonet-new.github.io#1]
I would add some more stuff on the homepage:
- there is no easy "download" / "installation instructions" available
- we should have at least a small snippet of a basic radio
- maybe have a "hall of fame" (something like "they are using it" and name big shots using Liquidsoap)
- the height of the picture above is a bit too big I find

**Comment by toots** [comment]
* yes
* yes
* I want to avoid the hall of fame for now because I don't want to hav to track/update it.
* Maybe 🙂
